---
global:
  pattern: multicloud-gitops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub

clusterSet:
  name: dr

managed1:
  name: dr-alpha
  clusterset: dr

managed2:
  name: dr-beta
  clusterset: dr

secretStore:
  name: vault-backend
  kind: ClusterSecretStore
