---
global:
  pattern: multicloud-gitops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub

managed1:
  name: dr-alpha
  clusterset: rdr

managed2:
  name: dr-beta
  clusterset: rdr

secretStore:
  name: vault-backend
  kind: ClusterSecretStore
