apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    cluster.open-cluster-management.io/managedCluster: {{ .Values.managed1.name }}
  name: {{ .Values.managed1.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    cluster.open-cluster-management.io/managedCluster: {{ .Values.managed2.name }}
  name: {{ .Values.managed2.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: {}
