apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auto-import-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: {{ .Values.managed1.name }} 
spec:
  dataFrom:
  - extract:
      # Expects entries called: aws_access_key_id and aws_secret_access_key
      key: {{ default "secret/hub/cluster1" .clusterKeyPath }}
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: auto-import-secret
    creationPolicy: Owner
    template:
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auto-import-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: {{ .Values.managed2.name }}
spec:
  dataFrom:
  - extract:
      # Expects entries called: aws_access_key_id and aws_secret_access_key
      key: {{ default "secret/hub/cluster2" .clusterKeyPath }}
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: auto-import-secret
    creationPolicy: Owner
    template:
      type: Opaque
