apiVersion: multicluster.odf.openshift.io/v1alpha1
kind: MirrorPeer
metadata:
  name: mirrorpeer-{{ .Values.managed1.name }}-{{ .Values.managed2.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  items:
  - clusterName: {{ .Values.managed1.name }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  - clusterName: {{ .Values.managed2.name }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  manageS3: true
  schedulingIntervals:
  - 2m
  - 5m
  - 15m
  type: async
