apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  name: 'drsync15m'
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  drClusters:
    - {{ .Values.managed1.name }}
    - {{ .Values.managed2.name }}
  schedulingInterval: 15m
---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  name: 'drsync5m'
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  drClusters:
    - {{ .Values.managed1.name }}
    - {{ .Values.managed2.name }}
  schedulingInterval: 5m
---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  name: 'drsync2m'
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  drClusters:
    - {{ .Values.managed1.name }}
    - {{ .Values.managed2.name }}
  schedulingInterval: 2m
