---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-sa
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patch-sa-role
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
rules:
  - apiGroups:
      - ""
      - "ocs.openshift.io"
      - "operator.openshift.io"
    resources:
      - consoles
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-sa-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
subjects:
  - kind: ServiceAccount
    name: patch-sa
    namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-sa-role
